### ISSUE TITLE
Add mercatormap to l3prefixes

### ISSUE THREAD

**Issue by pablgonz** [T-F-S/mercatormap#1]
Hi, could you add your packages to `l3prefixes.csv`.
Here's a link:

https://github.com/latex3/latex3/blob/master/l3kernel/doc/l3prefixes.csv

That file is for contact info, but also to keep track of the registered _prefixes_ in packages to avoid that two packages use the same prefix and clash.

Thank you so much for this package , they're great :)
Greetings
Pablo

**Comment by T-F-S** [comment]
Hi Pablo,
I already registered my packages some weeks ago :-)
But, thank you for reminding anyway.

**Comment by pablgonz** [comment]
Oh, now I've seen it :)
